on:
    workflow_dispatch:

jobs:
  parse-websites:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.website-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set websites matrix
        id: website-matrix
        run: echo "matrix=$(jq -c . < ./websites.json)" >> $GITHUB_OUTPUT

  axe-core-cli:
    needs: parse-websites
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.parse-websites.outputs.matrix)}}
    steps: 
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install axe-core/cli
          run: npm i @axe-core/cli -g
        - name: Cache chromedriver
          id: cache-chromedriver
          uses: actions/cache@v3
          with:
            path: /usr/local/bin/chromedriver
            key: ${{ runner.os }}-chromedriver
        - name: Install chromedriver
          if: steps.cache-chromedriver.outputs.cache-hit != 'true'
          uses: nanasess/setup-chromedriver@v2
        - name: Testing ${{ matrix.name }}
          id: test
          #run: axe ${{ matrix.url }} --chromedriver-path='/usr/local/bin/chromedriver' --dir reports/${{ matrix.name }} --save ${{ matrix.name }}-report-$(date +'%Y-%m-%dT%H:%M:%S').json
          run: echo "axe-result=test" >> $GITHUB_OUTPUT

        ## Write for matrix outputs workaround 
        - uses: cloudposse/github-action-matrix-outputs-write@main
          id: out
          with:
            matrix-step-name: ${{ github.job }}
            matrix-key: ${{ matrix.name }}
            outputs: |-
              result: ${{ steps.test.outputs.axe-result }}

  ## Read matrix outputs 
  read:
    runs-on: ubuntu-latest
    needs: [axe-core-cli]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: axe-core-cli

    outputs:
      result: "${{ steps.read.outputs.result }}"

  ## Output matrix results
  output:
    runs-on: ubuntu-latest
    needs: [read]
    steps:
      - run: echo ${{ fromJson(needs.read.outputs.result).result }}
